## 職業資訊告示牌
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/forest_archer"},"color":"blue"}',Text2:'{"text":"森林射手","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-森林射手"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/mage"},"color":"blue"}',Text2:'{"text":"魔法師","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-魔法師"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/miner"},"color":"blue"}',Text2:'{"text":"礦工","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-礦工"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/necromancer"},"color":"blue"}',Text2:'{"text":"死靈法師","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-死靈法師"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/paladin"},"color":"blue"}',Text2:'{"text":"聖騎士","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-聖騎士"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/priest"},"color":"blue"}',Text2:'{"text":"祭司","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-祭司"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/ronin"},"color":"blue"}',Text2:'{"text":"浪人武士","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-浪人武士"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/descriptions/shepherd"},"color":"blue"}',Text2:'{"text":"牧羊人","color":"#FFFFFF"}',Text3:'{"text":"獲得職業資訊","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業資訊-牧羊人"}'}}

## 職業體驗告示牌
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/forest_archer"},"color":"blue"}',Text2:'{"text":"森林射手","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-森林射手"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/mage"},"color":"blue"}',Text2:'{"text":"魔法師","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-魔法師"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/miner"},"color":"blue"}',Text2:'{"text":"礦工","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-礦工"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/necromancer"},"color":"blue"}',Text2:'{"text":"死靈法師","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-死靈法師"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/paladin"},"color":"blue"}',Text2:'{"text":"聖騎士","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-聖騎士"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/priest"},"color":"blue"}',Text2:'{"text":"祭司","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-祭司"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/ronin"},"color":"blue"}',Text2:'{"text":"浪人武士","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-浪人武士"}'}}
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/shepherd"},"color":"blue"}',Text2:'{"text":"牧羊人","clickEvent":{"action":"run_command","value":"tp 0 311 0"},"color":"#FFFFFF"}',Text3:'{"text":"前往體驗區","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-牧羊人"}'}}

## 離開體驗區告示牌
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================================","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/clearall"},"color":"blue"}',Text2:'{"text":"離開體驗區","clickEvent":{"action":"run_command","value":"tp 0 301 0"},"color":"#FFFFFF"}',Text3:'{"text":"選擇其他職業","clickEvent":{"action":"run_command","value":"function rpg:systems/test_item_remove"},"color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"職業體驗-離開"}'}}

## 體驗區資源包告示牌
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"=========================================","clickEvent":{"action":"run_command","value":"function rpg:systems/test_item"},"color":"blue"}',Text2:'{"text":"獲取資源包","color":"#FFFFFF"}',Text3:'{"text":""}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"資源包"}'}}

## 死靈系測試
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"=========================================","clickEvent":{"action":"run_command","value":"summon zombie ~ ~1 ~ {DeathLootTable:\\"0\\",IsBaby:false}"},"color":"blue"}',Text2:'{"text":"召喚死靈系生物","color":"#FFFFFF"}',Text3:'{"text":""}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"死靈系測試"}'}}

## 非死靈系測試
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"=========================================","clickEvent":{"action":"run_command","value":"summon spider ~ ~1 ~ {DeathLootTable:\\"0\\"}"},"color":"blue"}',Text2:'{"text":"召喚非死靈系生物","color":"#FFFFFF"}',Text3:'{"text":""}',Text4:'{"text":"==========================================","color":"blue"}'},display:{Name:'{"text":"非死靈系測試"}'}}

## 職業確認告示牌
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【森林射手】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以森林射手","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/forest_archer"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【魔法師】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以魔法師","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/mage"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【礦工】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以礦工","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/miner"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【死靈法師】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以死靈法師","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/necromancer"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【聖騎士】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以聖騎士","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/paladin"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【祭司】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以祭司","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/priest"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【浪人武士】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以浪人武士","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/ronin"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}
give @s spruce_sign{BlockEntityTag:{Text1:'{"text":"==========================","color":"red","clickEvent":{"action":"run_command","value":"tellraw @a [\\"\\",{\\"selector\\":\\"@s\\",\\"color\\":\\"gold\\"},{\\"text\\":\\"選擇【牧羊人】\\",\\"color\\":\\"gold\\"}]"}}',Text2:'{"text":"確定以牧羊人","color":"white","clickEvent":{"action":"run_command","value":"function rpg:professions/selectclass/shepherd"}}',Text3:'{"text":"為職業進行生存","color":"white"}',Text4:'{"text":"==========================","color":"red"}'}}

## 開始生存告示牌
give @s minecraft:spruce_sign{BlockEntityTag:{Text1:'{"text":"=========================================","clickEvent":{"action":"run_command","value":"effect give @s minecraft:slow_falling 40 0 true"},"color":"red"}',Text2:'{"text":"請先確認職業","clickEvent":{"action":"run_command","value":"tp 0 290 0"},"color":"#FFFFFF"}',Text3:'{"text":"然後按此開始生存","color":"#FFFFFF"}',Text4:'{"text":"==========================================","color":"red"}'},display:{Name:'{"text":"開始跳傘"}'}}



