## 偵測左右10格上下3格內的礦物
execute as @a store result score @s .coal_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:coal_ores force
execute as @a store result score @s .iron_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:iron_ores force
execute as @a store result score @s .copper_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:copper_ores force
execute as @a store result score @s .gold_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:gold_ores force
execute as @a store result score @s .redstone_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:redstone_ores force
execute as @a store result score @s .emerald_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:emerald_ores force
execute as @a store result score @s .lapis_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:lapis_ores force
execute as @a store result score @s .diamond_Miner_S1 run execute at @s run clone ~-10 ~-3 ~-10 ~10 ~3 ~10 ~-10 ~-3 ~-10 filtered #minecraft:diamond_ores force

tellraw @s ["",{"text":"礦物狀態","bold":true,"color":"green"},"\n",{"text":"煤礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".coal_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"鐵礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".iron_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"銅礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".copper_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"金礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".gold_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"紅石礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".redstone_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"綠寶石礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".emerald_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"青金石礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".lapis_Miner_S1"},"bold":true,"color":"white"},"\n",{"text":"鑽石礦: ","bold":true,"color":"green"},{"score":{"name":"@s","objective":".diamond_Miner_S1"},"bold":true,"color":"white"}]